export const CURATED_ICONS: readonly string[] = [
  // Weapons
  "broadsword",
  "battle-axe",
  "warhammer",
  "trident",
  "bow-arrow",
  "crossbow",
  "plain-dagger",
  "spear-hook",
  "scythe",
  "flail",
  "mace-head",
  "halberd",
  "sparkling-sabre",
  "wood-club",
  "whip",
  "glaive",
  "thrown-knife",
  "winged-scepter",
  "bowie-knife",
  "katana",
  // Armor
  "shield",
  "checked-shield",
  "barbute",
  "visored-helm",
  "chest-armor",
  "chain-mail",
  "leather-armor",
  "gauntlet",
  "cape",
  "boots",
  // Magic items
  "ring",
  "diamond-ring",
  "gem-pendant",
  "crystal-cluster",
  "wizard-staff",
  "magic-swirl",
  "scroll-unfurled",
  "spell-book",
  "crystal-ball",
  "magic-lamp",
  "necklace",
  "ankh",
  "rune-stone",
  "magic-portal",
  "magic-shield",
  // Consumables
  "potion-ball",
  "round-bottom-flask",
  "drink-me",
  "bottle-vapors",
  "vial",
  "meat",
  "bread",
  "shiny-apple",
  "honey-jar",
  "fizzing-flask",
  // Ammunition
  "arrow-cluster",
  "high-shot",
  "heavy-bullets",
  "thrown-spear",
  // Tools
  "lockpicks",
  "magnifying-glass",
  "rope-coil",
  "hand-saw",
  "anvil",
  "fishing-pole",
  "spade",
  "lantern-flame",
  "torch",
  "compass",
  // Magical effects
  "fire-flower",
  "ice-cube",
  "lightning-arc",
  "holy-symbol",
  "skull-crossed-bones",
  "evil-eyes",
  "moon",
  "sun",
  "snowflake-1",
  "tornado",
  // Creature parts
  "dragon-head",
  "wolf-head",
  "claws",
  "fangs",
  "horned-skull",
  // Containers
  "knapsack",
  "swap-bag",
  "locked-chest",
  "bloody-stash",
  "crystal-shrine",
] as const;

export type CuratedIconKey = (typeof CURATED_ICONS)[number];

export function isCurated(key: string): key is CuratedIconKey {
  return (CURATED_ICONS as readonly string[]).includes(key);
}
